### ISSUE TITLE
reloading while launching chat thread causes multiple reply from moderator

### ISSUE THREAD

**Issue by thammegowda** [isi-nlp/boteval#22]
The launch-thread takes a few seconds (maybe upto a minute) to get the initial reply from chatbot.
During this time, if the user reloads thread, it trigger generation of another reply.  

Here we request initialization of chat thread
https://github.com/isi-nlp/boteval/blob/3c9011e385e9dbe88404cd1f6d006bfe0a014234/boteval/controller.py#L280

here we try to cache and reuse dialog-manager object
https://github.com/isi-nlp/boteval/blob/3c9011e385e9dbe88404cd1f6d006bfe0a014234/boteval/service.py#L377-L385

This code is not thread-safe. 

Solution:
We need java equivalent of synchronized method[1].  In python, we can take advantage of mutex [2]. But there are two implementations: `threading.Lock` and `multiprocessing.Lock`. Not sure which one works in flask environment. 

[1] https://docs.oracle.com/javase/tutorial/essential/concurrency/syncmeth.html
[2] https://stackoverflow.com/a/3311157/1506477

**Comment by jonmay** [comment]
I observed messages coming in out-of-order on mturk after we merged this change.
was the out-of-order behavior reproducible?
