### ISSUE TITLE
enable launching many tasks at once 

### ISSUE THREAD

**Issue by wise-east** [isi-nlp/boteval#57]
right now, we have to create tasks for each individual conversation stubs separately and also launching them separately. 

This is not scalable if we want to scale our tasks to many more. 

While keeping the granular control over each task, it would be very useful to be able to launch many tasks at once with the same configuration so that we can conduct larger experiments more efficiently.

**Comment by River-vocal** [comment]
I may need clarification. Do you need a button to launch all the tasks that haven’t been launched yet? Or do you need a panel to create a list of tasks (from different topics) with the same configuration? Or both?

**Comment by wise-east** [comment]
taken care of with #65
