### ISSUE TITLE
link to docs not working 

### ISSUE THREAD

**Issue by wise-east** [isi-nlp/boteval#69]
@thammegowda could you help us figure out why https://cutelab.name/boteval/ returns a 404 error?

**Comment by thammegowda** [comment]
`docs/index.html` file is missing. It got deleted  (by accident ?) https://github.com/isi-nlp/boteval/commit/efd55ced9ee9fd22a94543a245d3a93b509eb4ab

There is index.html under `docs/v0.1` so -- https://cutelab.name/boteval/v0.1/ -- is valid.  
https://github.com/isi-nlp/boteval/blob/9394b87c5d26ab500f190641fdfb86ea2185b3c8/docs/build.sh#L42

could you please create a symlink manually and push it? 
See also https://github.com/isi-nlp/rtg/blob/master/docs/index.html for an example.

**Comment by wise-east** [comment]
great, thanks, it was fixed with 27a8b8
